### ISSUE TITLE
Drag & Drop Shortcode from Content Elements

### ISSUE THREAD

**Issue by andronic90** [ThemeFuse/Unyson-Builder-Extension#13]
In v 1.1.18 I can't drag & drop elements from Content Elements : https://static.md/307d75c8210f8267f84680e4e2ced63f.png only on click I can put shortcodes in page, but from Layout Elements I can drag elements and drop where I need.

**Comment by ghost** [comment]
https://github.com/ThemeFuse/Unyson-Builder-Extension/commit/db1fa3f1c64199d3c4210c56388579d369679ee0
