### ISSUE TITLE
Displaying Page Builder items outside of the loop

### ISSUE THREAD

**Issue by meta4creations** [ThemeFuse/Unyson-Builder-Extension#19]
I'm trying to display post content in various areas of my site using the get_post() function, but I'm having issues getting the Page Builder content to display.

I've attempted using:

`$my_posts = apply_filters( 'the_posts', array(get_post($id)), false );`

But, that doesn't seem to be working. Do you have any suggestions on implementing this in my site?

Thanks!

**Comment by ghost** [comment]
It is because of [PageBuilder 1.5.0 update](https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/185). This should work:

``` php
$posts = get_posts(array(
    'include' => 13,
    'post_type' => 'any',
    'numberposts' => 1,
    'suppress_filters' => false,
));

echo apply_filters('the_content', $posts[0]->post_content);
```

**Comment by meta4creations** [comment]
Thank you for the response! I was able to get that working on a single site, but I guess my issue is a bit more complex.

I am using a multisite install and am attempting to display content from one blog on another blog within the multisite. I am able to do this with normal content using the switch_to_blog() function, but I'm guessing there's filter or action that isn't firing for the page builder when attempting this. I am running Page Builder on all sites on the multisite.

Here is what I'm currently attempting:

```
// Switch to the parent site
switch_to_blog( 1 ); 

$posts = get_posts(array(
  'include' => 2273,
  'post_type' => 'defaults',
  'numberposts' => 1,
  'suppress_filters' => false,
));

echo apply_filters('the_content', $posts[0]->post_content);

// Switch back to child site
restore_current_blog();
```

Also, just to be clear on my full implementation, I have a custom Page Builder shortcode setup to choose content from the "main" blog, which would then appear within Page Builder content of the other sites. 

Currently, though, I am just testing this outside of the custom shortcode directly within a page template.

**Comment by ghost** [comment]
Yes, it's a bit complex. I will take a look but can't tell if it will be soon or not. You can try to inspect the code yourself https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/v1.5.0/class-fw-extension-page-builder.php#L322-L325

**Comment by ghost** [comment]
Until I will start working on this issue, try to do `FW_Cache::clear();` after blog switch before query, maybe it will help.

**Comment by meta4creations** [comment]
Thanks for the suggestion. I gave it a try and it didn’t seem to help, though.

This isn’t a high priority, so no worries if it takes awhile. I’ll try to spend some additional time with it myself to see if I can find a solution.

Thanks again!  

— Joe Anderson

http://www.metaphorcreations.com
http://themeforest.net/user/meta4creations/
http://codecanyon.net/user/joemc

**Comment by ghost** [comment]
It's not high priority, please inspect it yourself.

**Comment by ghost** [comment]
1. [These filters](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/v1.6.7/class-fw-extension-page-builder.php#L59-L62) should change post_content before display
2. If the filters doesn't work, use [this function](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/v1.6.7/helpers.php#L41)
