### ISSUE TITLE
problem after update 500 internal error

### ISSUE THREAD

**Issue by andronic90** [ThemeFuse/Unyson-Builder-Extension#22]
Hello, after update extensions to the latest problem I have this problem : http://screencast.com/t/S3PGajgytTVc , please inspect where is the problem, If you need more details please contact me in PM

**Comment by ghost** [comment]
Maybe there is something in theme. Have you tested your theme on localhost with latest Unyson extensions?

**Comment by andronic90** [comment]
sorry I fixed the problem. Andrei know about problem, please update contact form docs
