### ISSUE TITLE
Add feedback when user click on builder items which are not allowed as first level item

### ISSUE THREAD

**Issue by dinhtungdu** [ThemeFuse/Unyson-Builder-Extension#24]
Hi, I'm building a builder using Unyson builder extension.

I have an item type called `section` and I make it as fist level, all other type are second level and must be nested inside first level item.

My question is: Is there a way to provide feedback/message to end user when they click on second level item?

Now when user click on second level item, nothing happen ( except log in the console: https://goo.gl/Jg82O8) then they think my builder doesn't work. I think an alert message or some thing like that will be very helpful.

I'm using latest stable releases: WordPress 4.7.5 | Unyson 2.6.16.
My dev environment: Mac OSX 10.11.6, Google Chrome Version 58.0.3029.110 (64-bit), PHP 7.0.18 (cli) (built: Apr 16 2017 12:12:20)

**Comment by ViorelEremia** [comment]
I close your issue for now; if you did not solve it please reopen it and provide more details the phpcode for item type section js.
