### ISSUE TITLE
Prebuilt Layouts / Template Manager

### ISSUE THREAD

**Issue by thanhluu** [ThemeFuse/Unyson-Builder-Extension#5]
Do you have any plan to add this feature to Unyson Page Builder Extension? As a theme maker, I need this feature to add some prebuilt layouts for user

Example:
http://codecanyon.net/item/templatera-template-manager-for-visual-composer/5195991
https://siteorigin.com/page-builder/documentation/prebuilt-layouts/

**Comment by ghost** [comment]
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/33
